# Kubernetes Cert
cert:
  # 签发集群整数保存目录，默认签发10年有限期证书
  dir: /opt/certs
  # 签发证书大小
  size: 2048
  # 签发证书的时间
  day: 3650d

# Etcd
etcd:
  # etcd 安装包下载地址
  # 如使用自建文件服务器，请保证下载路径为:{{etcd.download_url}}/{{etcd.version}}/etcd-{{etcd.version}}-linux-amd64.tar.gz
  download_url: https://ghproxy.com/https://github.com/etcd-io/etcd/releases/download
  # etcd 版本
  version: v3.5.3
  # etcd 数据目录，如使用多个目录映射同一块数据盘的方式，请勿修改默认目录
  data_dir: "/var/lib/etcd"

# High Availability
# kube-apiserver负载均衡的信息
# 如使用haproxy + keepalived请填写VIP及端口
# 如使用公有云负载均衡请填写负载均衡IP及端口（需再安装之前自行配置）
# 如使用域名，需提前配置解析。不使用域名时，请注释掉
# 如使用haproxy + keepalived ，并且跟master节点部署在一起时，请修改port以避免端口冲突
loadbalance:
  ip: 172.16.90.100
  port: 6443
  #domain_name: apiserver.mafic.com

# Kubernetes
kubernetes:
  # kubernetes 二进制安装包下载地址，默认为阿里云从Google同步过来的镜像，更新较慢，最新版本可能未同步过来。
  # 如使用自建文件服务器，请保证下载路径为:{{kubernetes.download_url}}/{{kubernetes.version}}/bin/linux/amd64/kube-apiserver。
  download_url: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release
  # kubernetes 版本
  version: v1.24.2
  # 集群Pod网段
  podSubnet: 10.64.0.0/16
  # 集群Service网段
  serviceSubnet: 192.168.0.0/20
  # kubelet 数据目录，如使用多个目录映射同一块数据盘的方式，请勿修改默认目录
  kubelet_dir: "/var/lib/kubelet"

# container runtime
runc:
  # runc 安装包下载地址
  # 如使用自建文件服务器，请保证下载路径为:{{runc.download_url}}/{{runc.version}}/runc.amd64
  download_url: https://ghproxy.com/https://github.com/opencontainers/runc/releases/download
  # runc 版本
  version: v1.1.3

cniplugins:
  # cni-plugins 安装包下载地址
  # 如使用自建文件服务器，请保证下载路径为:{{cniplugins.download_url}}/{{cniplugins.version}}/cni-plugins-linux-amd64-{{cniplugins.version}}.tgz
  download_url: https://ghproxy.com/https://github.com/containernetworking/plugins/releases/download
  # cni-plugins 版本
  version: v1.1.1

critools:
  # cri-tools 安装包下载地址
  # 如使用自建文件服务器，请保证下载路径为:{{critools.download_url}}/{{critools.version}}/crictl-{{critools.version}}-linux-amd64.tar.gz
  download_url: https://ghproxy.com/https://github.com/kubernetes-sigs/cri-tools/releases/download
  # cri-tools 版本
  version: v1.24.2

# Use cri-containerd-cni, Contains cni-plugins: https://github.com/containernetworking/plugins
containerd:
  # containerd 安装包下载地址
  # 如使用自建文件服务器，请保证下载路径为:{{containerd.download_url}}/v{{containerd.version}}/containerd-{{containerd.version}}-linux-amd64.tar.gz
  download_url: https://ghproxy.com/https://github.com/containerd/containerd/releases/download
  # containerd 版本,建议使用1.5.0以上版本
  version: 1.6.6
  # containerd 持久化数据目录，如使用多个目录映射同一块数据盘的方式，请勿修改默认目录
  root: "/var/lib/containerd"
  # containerd 临时数据目录
  state: "/run/containerd"
  # containerd oom_score
  oom_score: -999
  grpc:
    max_recv_message_size: 16777216
    max_send_message_size: 16777216
  debug:
    level: ""
  metrics:
    address: ""
    grpc_histogram: false
  cri:
    sandbox_image: "registry.aliyuncs.com/google_containers/pause:3.7"
    max_container_log_line_size: -1
  containerd:
    snapshotter: overlayfs
  options:
    #BinaryName = "nvidia-container-runtime"
    SystemdCgroup: true
  registries:
    "docker.io": "https://registry-1.docker.io"
    "k8s.gcr.io": "https://registry.aliyuncs.com/k8sxio"

# Network Plugin
network_plugin: calico
# cilium need linux kernel >= 4.9.17
# 暂不推荐使用，后续测试通过再加入
#cilium:
  #version: v1.11.6
  # {{cilium.registry}}/operator-generic:{{cilium.version}}
  # {{cilium.registry}}/cilium:{{cilium.version}}
  # {{cilium.registry}}/istio_proxy:{{cilium.version}}
  #registry: docker.mirrors.sjtug.sjtu.edu.cn/cilium
  # "disabled" or "vxlan" or "geneve"
  #network_mode: vxlan
flannel:
  version: v0.18.1
  # {{flannel.registry}}/flannel-cni-plugin:v1.0.1
  # {{flannel.registry}}/flannel:{{flannel.version}}
  registry: docker.mirrors.sjtug.sjtu.edu.cn/flannelcni
  # "vxlan" or "host-gw"
  network_mode: vxlan
calico:
  version: v3.23.1
  # {{calico.registry}}/kube-controllers:{{calico.version}}
  # {{calico.registry}}/node:{{calico.version}}
  # {{calico.registry}}/cni:{{calico.version}}
  registry: docker.mirrors.sjtug.sjtu.edu.cn/calico
  # "ipip" or "bgp" or "mix"
  network_mode: ipip
  # 可指定网卡或使用can-reach=网关
  ip_autodetection_method: interface=eth0

# Addons
coredns:
  version: 1.8.6
  # {{coredns.registry}}/coredns:{{coredns.version}}
  registry: docker.mirrors.sjtug.sjtu.edu.cn/coredns
helm:
  enabled: true
  # 如使用自建文件服务器，请保证下载路径为:{{helm.download_url}}/{{helm.version}}/helm-{{helm.version}}-linux-amd64.tar.gz
  download_url: https://mirrors.huaweicloud.com/helm
  version: v3.8.2
nodelocaldns:
  enabled: true
  version: 1.21.1
  # {{nodelocaldns.registry}}/k8s-dns-node-cache:{{nodelocaldns.version}}
  registry: k8s-gcr-io.mirrors.sjtug.sjtu.edu.cn/dns
  ip: 169.254.20.10
metrics_server:
  enabled: true
  version: v0.6.1
  # {{metrics_server.registry}}/metrics-server:{{metrics_server.version}}
  registry: k8s-gcr-io.mirrors.sjtug.sjtu.edu.cn/metrics-server
nvidia_device_plugin:
  enabled: false
  version: v0.11.0
  # {{nvidia_device_plugin.registry}}/k8s-device-plugin:{{nvidia_device_plugin.version}}
  registry: nvcr.io/nvidia
