# Kubernetes Cert
cert:
  # 签发集群整数保存目录，默认签发10年有限期证书
  dir: /etc/ssl/kube-certs
  # 签发证书大小
  size: 2048

# Etcd
etcd:
  # etcd 版本
  version: 3.4.13
  # etcd 数据目录
  data_dir: "/var/lib/etcd"

# Kubernetes
# kubernetes 下载服务器地址，默认的下载服务器比较慢，建议按照文档自建
kube_down_url: http://dl.k8sre.com/k8s
kubernetes:
  # kubernetes 版本
  version: v1.20.4
  # 集群Pod网段
  podSubnet: 10.64.0.0/12
  # 集群Service网段
  serviceSubnet: 10.80.0.0/16
  # kubelet 数据目录
  kubelet_dir: "/var/lib/kubelet"
  # kube-apiserver的访问域名，需提前配置解析。不使用域名时，可以指定为负载均衡的IP（本Playbook需指定为haproxy的VIP）
  apiserver_domain_name: apiserver.k8sre.com
  # cni-plugins: https://github.com/containernetworking/plugins
  cni_plugins_version: v0.8.7

# Containerd
critools_version: v1.20.0
# containerd 版本
containerd_version: 1.4.3
containerd_root: "/var/lib/containerd"
containerd_state: "/run/containerd"
containerd_config:
  grpc:
    max_recv_message_size: 16777216
    max_send_message_size: 16777216
  debug:
    level: ""
  cri:
    sandbox_image: "registry.aliyuncs.com/google_containers/pause:3.3"
    max_container_log_line_size: -1
  containerd:
    snapshotter: overlayfs
  options:
    SystemdCgroup: "true"
  registries:
    "docker.io": "https://dockerhub.mirrors.nwafu.edu.cn"
    "k8s.gcr.io": "https://registry.aliyuncs.com/k8sxio"

# Network Plugin
network_plugin: calico
calico:
  version: v3.17.0
  network_mode: ipip
flannel:
  version: v0.13.0
  network_mode: vxlan
# cilium need linux kernel >= 4.9.17
cilium:
  version: v1.9.3

# Addons
coredns:
  version: 1.7.0
  enable_nodelocaldns: false
  nodelocaldns_ip: "169.254.20.10"
metrics_server:
  version: v0.4.1
