---
- name: "Deploying Kubernetes High Availability Cluster with Ansible Playbook"
  hosts: etcd master node haproxy
  roles:
    - { role: 'init', tags: "init", when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }

- name: "签发证书"
  hosts: localhost
  connection: local
  roles:
    - { role: 'cert', tags: "cert" }

- name: "部署haproxy"
  hosts: haproxy
  roles:
    - { role: 'haproxy', tags: "install_haproxy", when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }
    - { role: 'keepalived', tags: "install_keepalived", when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }

- name: "部署etcd"
  hosts: etcd
  roles:
    - { role: 'etcd', tags: "install_etcd", when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }

- name: "部署master"
  hosts: master
  roles:
    - { role: 'master', tags: "install_master", when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }

- name: "部署node"
  hosts: master node
  roles:
    - { role: 'containerd', tags: "install_containerd", when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }
    - { role: 'critools', tags: "install_critools", when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }
    - { role: 'node', tags: "install_node", when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }

- name: "部署addons"
  hosts: "{{groups['master'][0]}}"
  roles:
    - { role: 'addons', tags: "install_addons", when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'" }
