- name: Get cri-tools
  get_url:
    url: "{{ kube_down_url }}/cri-tools/{{critools_version}}/crictl-{{critools_version}}-linux-amd64.tar.gz"
    dest: /tmp/
  tags: cri_tools

- name: "Config cri-tools"
  template:
    src: "crictl.yaml.j2"
    dest: "/etc/crictl.yaml"
    owner: root
    group: root
    mode: 0644
  tags: cri_tools

- name: Install cri-tools
  unarchive:
    src: "/tmp/crictl-{{critools_version}}-linux-amd64.tar.gz"
    dest: /usr/bin/
    remote_src: yes
  tags: cri_tools
  notify:
    - Get crictl completion
    - Install crictl completion
