- name: "下载etcd安装包"
  get_url:
    url: "https://mirrors.huaweicloud.com/etcd/v{{ etcd.version }}/etcd-v{{ etcd.version }}-linux-amd64.tar.gz"
    dest: /tmp/

- name: "解压etcd安装包"
  unarchive:
    src: "/tmp/etcd-v{{ etcd.version }}-linux-amd64.tar.gz"
    dest: /tmp/
    copy: no

- name: "安装etcd"
  copy:
    src: "{{ item.src }}"
    dest: "/usr/local/bin/"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  with_items:
    - {src: "/tmp/etcd-v{{ etcd.version }}-linux-amd64/etcd"}
    - {src: "/tmp/etcd-v{{ etcd.version }}-linux-amd64/etcdctl"}

- name: "分发证书"
  copy:
    src: "{{ item.line }}"
    dest: "/etc/kubernetes/pki/"
  with_items:
    - {line: '{{ cert.dir }}/etcd-ca.pem'}
    - {line: '{{ cert.dir }}/{{ ansible_default_ipv4.address }}/etcd-server.pem'}
    - {line: '{{ cert.dir }}/{{ ansible_default_ipv4.address }}/etcd-server.key'}
    - {line: '{{ cert.dir }}/{{ ansible_default_ipv4.address }}/etcd-peer.pem'}
    - {line: '{{ cert.dir }}/{{ ansible_default_ipv4.address }}/etcd-peer.key'}
    - {line: '{{ cert.dir }}/{{ ansible_default_ipv4.address }}/etcd-healthcheck-client.pem'}
    - {line: '{{ cert.dir }}/{{ ansible_default_ipv4.address }}/etcd-healthcheck-client.key'}
  tags: dis_certs

- name: "创建etcd数据目录"
  file:
    path: "{{ etcd.data_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: "生成etcd配置文件"
  template:
    src: "etcd.service.j2"
    dest: "/usr/lib/systemd/system/etcd.service"
  notify:
    - restart etcd
