---
- name: Macvlan | Retrieve Pod Cidr
  command: "kubectl get nodes {{ ansible_hostname.split('-')[-2:] | join('-') | lower  }}-{{ ansible_default_ipv4.address }} -o jsonpath='{.spec.podCIDR}'"
  changed_when: false
  register: node_pod_cidr_cmd
  delegate_to: "{{ groups['master'][0] }}"

- name: Macvlan | set node_pod_cidr
  set_fact:
    node_pod_cidr={{ node_pod_cidr_cmd.stdout }}

- name: Macvlan | Retrieve default gateway network interface
  become: false
  raw: ip -4 route list 0/0 | sed 's/.*dev \([[:alnum:]]*\).*/\1/'
  changed_when: false
  register: node_default_gateway_interface_cmd

- name: Macvlan | set node_default_gateway_interface
  set_fact:
    node_default_gateway_interface={{ node_default_gateway_interface_cmd.stdout | trim }}

- block:
- name: Macvlan | Add interface for Macvlan
  command: "ip link add macvlan0 link {{ node_default_gateway_interface }} type macvlan mode {{ macvlan.mode }}"
  changed_when: false

- name: Macvlan | Install cni definition for Macvlan
  template:
    src: 10-macvlan.conf.j2
    dest: /etc/cni/net.d/10-macvlan.conf
    mode: 0644

- name: Macvlan | Install loopback definition for Macvlan
  template:
    src: 99-loopback.conf.j2
    dest: /etc/cni/net.d/99-loopback.conf
    mode: 0644

- name: Enable net.ipv4.conf.all.arp_notify in sysctl
  sysctl:
    name: net.ipv4.conf.all.arp_notify
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
