---
- name: Macvlan | restart network
  command: /bin/true
  notify:
    - Macvlan | reload network
  when: not ansible_os_family in ["Flatcar", "Flatcar Container Linux by Kinvolk"]

- name: Macvlan | reload network
  systemd:
    name: >-
      {% if ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky'] and ansible_distribution_major_version == "8" -%}
      NetworkManager
      {%- elif ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky'] -%}
      network
      {%- elif ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic" -%}
      systemd-networkd
      {%- elif ansible_os_family == "Debian" -%}
      networking
      {%- endif %}
    state: restarted
  when: not ansible_os_family in ["Flatcar", "Flatcar Container Linux by Kinvolk"] and network_plugin not in ['canal', 'calico']
