---
- name: kube-router | Create manifest
  template:
    src: kube-router.yml.j2
    dest: "/tmp/kube-router.yml"
    mode: 0644
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  notify:
    - reset_kube_router

- name: kube-router | Apply manifest
  shell: "kubectl apply -f /tmp/kube-router.yml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
