---
- name: kube-router | Create manifest
  template:
    src: kube-router.yaml.j2
    dest: "/tmp/kube-router.yaml"
    mode: 0644
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  notify:
    - reset_kube_router
  tags:
    - kube_router
    - kube_router_yaml

- name: kube-router | Apply manifest
  shell: "kubectl apply -f /tmp/kube-router.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags:
    - kube_router
    - kube_router_install
