- name: "生成coredns部署文件"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "coredns.yaml.j2", dest: "/tmp/coredns.yaml"}
  tags: coredns

- name: "部署coredns"
  shell: "kubectl apply -f /tmp/coredns.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: coredns
