- name: "添加Docker软件源"
  yum_repository:
    file: docker-ce
    name: "docker-ce-stable"
    description: "Docker CE Stable - $basearch"
    baseurl: "https://mirrors.aliyun.com/docker-ce/linux/centos/7/$basearch/stable"
    gpgkey: "https://mirrors.aliyun.com/docker-ce/linux/centos/gpg"
    gpgcheck: yes
    enabled: yes
  tags: docker_repo

- name: "安装containerd"
  yum:
    update_cache: yes
    enablerepo: docker-ce-stable
    name: 'containerd.io{% if containerd_version is defined and containerd_version != ""  %}-{{ containerd_version }}{% endif %}'
    state: installed
  tags: install_containerd

- name: "创建containerd配置目录"
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - {path: "/etc/containerd"}
    - {path: "{{ containerd_root }}"}
  tags: containerd_config

- name: "生成containerd配置文件"
  template:
    src: "config.toml.j2"
    dest: "/etc/containerd/config.toml"
    owner: root
    group: root
    mode: 0644
  tags: containerd_config
  notify:
    - restart containerd
